[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
# Use rustflags to pass the actual linker to ldproxy
rustflags = [
    "-C", "link-arg=--ldproxy-linker=xtensa-esp32-elf-gcc",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32"
ESP_IDF_VERSION = "v5.1.2"
